name: frontend_ci

on:
  push:
    branches:
      - dev/FE
    paths: 'frontend/**'
  pull_request:
    branches:
      - dev/FE
    paths: 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend
    steps:
      - name: Checkout code
      - uses: actions/checkout@v3

      - name: 의존성을 설치한다
        run: npm install

      - name: 테스트를 수행한다
        run: npm run test
