name: BE deploy CI on Pull Request

on:
  pull_request:
    branches: [ "deploy/BE" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2.6.0
    - name: Execute Gradle build
      run: |
        cd backend/baton
        ./gradlew build
