name: All deploy CI + CD on push

on:
  push:
    branches: [ "deploy/BE" ]

jobs:
  deploy-ci:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.SUBMODULE_BE_TOKEN }}
          submodules: true

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.6.0
      - name: Execute Gradle build
        run: |
          cd backend/baton
          ./gradlew build

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2.9.1

      - name: Login to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_DEPLOY_USERNAME }}
          password: ${{ secrets.DOCKERHUB_DEPLOY_TOKEN }}

      - name: Docker Image Build
        run: |
          cd backend/baton
          docker build --platform linux/arm64/v8 -t 2023batondeploy/2023-baton-deploy -f Dockerfile-deploy .

      - name: Docker Hub Push
        run: docker push 2023batondeploy/2023-baton-deploy

  deploy-cd:
    needs: deploy-ci
    runs-on: [self-hosted, Linux, ARM64, deploy]

    steps:
      - name: Pull Latest Docker Image
        run: |
          sudo docker login --username ${{ secrets.DOCKERHUB_DEPLOY_USERNAME }} --password ${{ secrets.DOCKERHUB_DEPLOY_TOKEN }}
          if sudo docker inspect spring-baton &>/dev/null; then
            sudo docker stop spring-baton
            sudo docker rm -f spring-baton
            sudo docker image prune -af
          fi
          sudo docker pull 2023batondeploy/2023-baton-deploy:latest

      - name: Docker Compose
        run: |
          sudo docker run --name spring-baton -v /home/ubuntu/logs:/app/logs -p 8080:8080 -e TZ=Asia/Seoul 2023batondeploy/2023-baton-deploy:latest 1>> build.log 2>> error.log &
