name: dev/BE CD on Push

on:
  push:
    branches: [ "dev/BE" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.SUBMODULE_BE_TOKEN }}
          submodules: recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.6.0
      - name: Execute Gradle build
        run: |
          cd backend/baton
          ./gradlew build

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2.9.1

      - name: Login to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_DEV_USERNAME }}
          password: ${{ secrets.DOCKERHUB_DEV_TOKEN }}

      - name: Docker Image Build
        run: |
          cd backend/baton
          docker build --platform linux/arm64/v8 -t 2023baton/2023baton -f Dockerfile-dev .

      - name: Docker Hub Push
        run: docker push 2023baton/2023baton

  deploy:
    runs-on: [ self-hosted, Linux, ARM64, dev ]
    needs: build

    steps:

      - name: Pull Latest Docker Image
        run: |
          sudo docker login --username ${{ secrets.DOCKERHUB_DEV_USERNAME }} --password ${{ secrets.DOCKERHUB_DEV_TOKEN }}
          sudo docker pull 2023baton/2023baton:latest

      - name: Docker Compose
        run: |
          /home/ubuntu/zero-downtime-deploy.sh
          sudo docker image prune -af
